version: "3.9"

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - vt_shared_network

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    networks:
      - vt_shared_network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: django_backend       # optional, but gives a stable hostname
    volumes:
      - ./backend:/app
      - ./backend/media:/app/media
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    depends_on:
      - db
      - redis
    networks:
      vt_shared_network:
        aliases:
          - django_backend_vt      # frontend will use this name to reach the API

volumes:
  postgres_data:

networks:
  vt_shared_network:
    external: true
